name: meed
description: The official MEED (Management of Emergencies in Eating Disorders) Risk Assessment Tool and %MedianBMI Calculator.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <=3.3.8"

dependencies:
  intl: ^0.17.0
  timeago: ^2.0.24
  font_awesome_flutter: ^10.2.1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Montserrat/static/Montserrat-Italic.ttf
          style: italic
        
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Open_Sans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway/Raleway-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-BoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Raleway/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway/Raleway-ThinItalic.ttf
          weight: 100
          style: italic


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/rcpch-logo.jpg
    - assets/images/rcpsych-logo-homepage-2022.jpg
    - assets/fonts/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
