import 'package:flutter/material.dart';
import 'package:line_awesome_icons/line_awesome_icons.dart';

class Risk {
  final String category;
  final String colour;
  final String description;
  final String grade;
  final Color selectedColour;
  final Color selectedPaleColour;

  Risk(this.category, this.colour, this.description, this.grade,
      this.selectedColour, this.selectedPaleColour);
}

class RiskCategory {
  final String category;
  final IconData icon;
  final Risk red;
  final Risk amber;
  final Risk green;
  final Risk blue;
  final Risk unscored;

  RiskCategory(this.category, this.icon, this.red, this.amber, this.green,
      this.blue, this.unscored);
}

List<Risk> scoredCategories = [
  marsipanRisks[4],
  marsipanRisks[9],
  marsipanRisks[14],
  marsipanRisks[19],
  marsipanRisks[24],
  marsipanRisks[29],
  marsipanRisks[34],
  marsipanRisks[39],
  marsipanRisks[44],
  marsipanRisks[49],
  marsipanRisks[54],
  marsipanRisks[59],
  marsipanRisks[64]
];

List<RiskCategory> marsipanCategories = [
  RiskCategory('Body Mass', LineAwesomeIcons.balance_scale, marsipanRisks[0],
      marsipanRisks[1], marsipanRisks[2], marsipanRisks[3], marsipanRisks[4]),
  RiskCategory(
      'Cardiovascular Health',
      LineAwesomeIcons.heart,
      marsipanRisks[5],
      marsipanRisks[6],
      marsipanRisks[7],
      marsipanRisks[8],
      marsipanRisks[9]),
  RiskCategory(
      'ECG Abnormalities',
      LineAwesomeIcons.heartbeat,
      marsipanRisks[10],
      marsipanRisks[11],
      marsipanRisks[12],
      marsipanRisks[13],
      marsipanRisks[14]),
  RiskCategory(
      'Hydration Status',
      LineAwesomeIcons.tint,
      marsipanRisks[15],
      marsipanRisks[16],
      marsipanRisks[17],
      marsipanRisks[18],
      marsipanRisks[19]),
  RiskCategory(
      'Temperature',
      Icons.ac_unit,
      marsipanRisks[20],
      marsipanRisks[21],
      marsipanRisks[22],
      marsipanRisks[23],
      marsipanRisks[24]),
  RiskCategory(
      'Biochemical Abnormalities',
      LineAwesomeIcons.ambulance,
      marsipanRisks[25],
      marsipanRisks[26],
      marsipanRisks[27],
      marsipanRisks[28],
      marsipanRisks[29]),
  RiskCategory(
      'Calorie Intake',
      LineAwesomeIcons.battery_half,
      marsipanRisks[30],
      marsipanRisks[31],
      marsipanRisks[32],
      marsipanRisks[33],
      marsipanRisks[34]),
  RiskCategory(
      'Engagement With Management Plan',
      LineAwesomeIcons.comments,
      marsipanRisks[35],
      marsipanRisks[36],
      marsipanRisks[37],
      marsipanRisks[38],
      marsipanRisks[39]),
  RiskCategory(
      'Activity and Exercise',
      LineAwesomeIcons.bicycle,
      marsipanRisks[40],
      marsipanRisks[41],
      marsipanRisks[42],
      marsipanRisks[43],
      marsipanRisks[44]),
  RiskCategory(
      'Self Harm and Suicide',
      LineAwesomeIcons.frown_o,
      marsipanRisks[45],
      marsipanRisks[46],
      marsipanRisks[47],
      marsipanRisks[48],
      marsipanRisks[49]),
  RiskCategory(
      'Muscular Weakness',
      LineAwesomeIcons.hand_grab_o,
      marsipanRisks[50],
      marsipanRisks[51],
      marsipanRisks[52],
      marsipanRisks[53],
      marsipanRisks[54]),
  RiskCategory(
      'Other Mental Health Diagnoses',
      LineAwesomeIcons.hand_peace_o,
      marsipanRisks[55],
      marsipanRisks[56],
      marsipanRisks[57],
      marsipanRisks[58],
      marsipanRisks[59]),
  RiskCategory(
      'Other',
      LineAwesomeIcons.stethoscope,
      marsipanRisks[60],
      marsipanRisks[61],
      marsipanRisks[62],
      marsipanRisks[63],
      marsipanRisks[64])
];

List<Risk> marsipanRisks = [
  Risk(
      'Body Mass',
      'Red',
      'Percentage Median BMI <70 [Approximates to below 0.4th BMI centile] OR Recent loss of weight of 1kg or more/week for two consecutive weeks',
      '',
      Colors.red,
      Colors.red.shade100),
  Risk(
      'Body Mass',
      'Amber',
      'Percentage Median BMI 70-80% [Approximates to between 2nd and 0.4th BMI centile] OR Recent loss of weight of 500g-999g/week for two consecutive weeks',
      '',
      Colors.amber,
      Colors.amber.shade100),
  Risk(
      'Body Mass',
      'Green',
      'Percentage Median BMI 80-85% [Approximates to between 9th and 2nd BMI centile] OR Recent weight loss of up to 500g/week for two consecutive weeks',
      '',
      Colors.green,
      Colors.green.shade100),
  Risk(
      'Body Mass',
      'Blue',
      'Percentage Median BMI>85% [Approximates to above 9th BMI centile] OR No weight loss over past two weeks',
      '',
      Colors.blue,
      Colors.blue.shade100),
  Risk('Body Mass', 'White', 'Unscored', '0', Colors.white, Colors.white),
  Risk(
      'Cardiovascular Health',
      'Red',
      'Heart rate (awake) <40 bpm. History of Recurrent Syncope. Marked orthostatic changes (fall in systolic blood pressure of 20mmHg or more, or below 0.4th-2nd centiles for age, or increase in heart rate up to 30bpm)',
      '',
      Colors.red,
      Colors.red.shade100),
  Risk(
      'Cardiovascular Health',
      'Amber',
      'Heart rate (awake) 40-50bpm. Sitting Blood Pressure: Systolic below 0.4th centile (84-98mmHg depending on age and sex). Diastolic: below 0.4th centile (35-40 mmHg depending on age and sex). Moderate orthostatic cardiovascular changes (fall in systolic blood pressure of 15mmHg or more, or diastolic blood pressure fall of 10mmHg or more within 3 mins standing, or increase in heart rate up to 30bpm). Occasional syncope',
      '',
      Colors.amber,
      Colors.amber.shade100),
  Risk(
      'Cardiovascular Health',
      'Green',
      'Heart rate (awake) 50-60bpm. Sitting Blood Pressure: Systolic below 2nd centile (88 - 105mmHg depending on age and sex), Diastolic below 2nd centile (40 - 45mmHg depending on age and sex). Pre-syncopal symptoms but no orthostatic cardiovascular changes. Cool peripheries.<br>Prolonged peripheral capillary refill time (normal central capillary refill time)',
      '',
      Colors.green,
      Colors.green.shade100),
  Risk(
      'Cardiovascular Health',
      'Blue',
      'Heart rate (awake) >60bpm. Normal sitting blood pressure for age and sex with reference to centile charts. Normal orthostatic cardiovascular changes. Normal heart rhythm',
      '',
      Colors.blue,
      Colors.blue.shade100),
  Risk('Cardiovascular Health', 'White', 'Unscored', '0', Colors.white,
      Colors.white),
  Risk(
      'ECG Abnormalities',
      'Red',
      'Irregular heart rhythm (does not include sinus arrhythmia). QTc >450 ms with evidence of bradyarrhythmia or tachyarrhythmia (excludes sinus bradycardia and sinus arrhythmia). ECG evidence of biochemical abnormality',
      '',
      Colors.red,
      Colors.red.shade100),
  Risk('ECG Abnormalities', 'Amber', 'QTc >450ms', '', Colors.amber,
      Colors.amber.shade100),
  Risk(
      'ECG Abnormalities',
      'Green',
      'QTc < 450ms AND taking medication known to prolong QTc interval. Family history of prolonged QTc or deafness',
      '',
      Colors.green,
      Colors.green.shade100),
  Risk('ECG Abnormalities', 'Blue', 'QTc < 450ms', '', Colors.blue,
      Colors.blue.shade100),
  Risk('ECG Abnormalities', 'White', 'Unscored', '0', Colors.white,
      Colors.white),
  Risk(
      'Hydration Status',
      'Red',
      'Severe dehydration (10%): Reduced urine output, Dry mouth, Decreased skin turgor, sunken eyes, Tachypnoea, Tachycardia',
      '',
      Colors.red,
      Colors.red.shade100),
  Risk(
      'Hydration Status',
      'Amber',
      'Moderate dehydration (5-10%). Reduced urine output. Dry mouth. Normal skin turgor. Some tachypnoea. Some tachycardia. Peripheral oedema',
      '',
      Colors.amber,
      Colors.amber.shade100),
  Risk(
      'Hydration Status',
      'Green',
      'Mild (less than 5%). May have dry mouth or not clinically dehydrated but with concerns about risk of dehydration with negative fluid balance.',
      '',
      Colors.green,
      Colors.green.shade100),
  Risk('Hydration Status', 'Blue', 'Not clinically dehydrated', '', Colors.blue,
      Colors.blue.shade100),
  Risk(
      'Hydration Status', 'White', 'Unscored', '0', Colors.white, Colors.white),
  Risk(
      'Temperature',
      'Red',
      'below 35.5 degrees Celsius (tympanic) OR below 35.0 degrees Celsius axillary',
      '',
      Colors.red,
      Colors.red.shade100),
  Risk('Temperature', 'Amber', 'below 36 degrees Celsius', '', Colors.amber,
      Colors.amber.shade100),
  Risk('Temperature', 'Green', 'Normal', '', Colors.green,
      Colors.green.shade100),
  Risk('Temperature', 'Blue', 'Normal', '', Colors.blue, Colors.blue.shade100),
  Risk('Temperature', 'White', 'Unscored', '0', Colors.white, Colors.white),
  Risk(
      'Biochemical Abnormalities',
      'Red',
      'Hypophosphataemia, Hypokalaemia, Hyponatraemia, Hypocalcaemia',
      '',
      Colors.red,
      Colors.red.shade100),
  Risk(
      'Biochemical Abnormalities',
      'Amber',
      'Hypophosphataemia. Hypokalaemia. Hyponatraemia. Hypocalcaemia.',
      '',
      Colors.amber,
      Colors.amber.shade100),
  Risk('Biochemical Abnormalities', 'Green', 'Normal Results', '', Colors.green,
      Colors.green.shade100),
  Risk('Biochemical Abnormalities', 'Blue', 'Normal Results', '', Colors.blue,
      Colors.blue.shade100),
  Risk('Biochemical Abnormalities', 'White', 'Unscored', '0', Colors.white,
      Colors.white),
  Risk(
      'Calorie Intake',
      'Red',
      'Acute food refusal OR estimated calorie intake 400-600kcal per day',
      '',
      Colors.red,
      Colors.red.shade100),
  Risk(
      'Calorie Intake',
      'Amber',
      'Severe restriction (less than 50% of required intake). Vomiting. Purging with laxatives',
      '',
      Colors.amber,
      Colors.amber.shade100),
  Risk('Calorie Intake', 'Green', 'Moderate restriction. Bingeing.', '',
      Colors.green, Colors.green.shade100),
  Risk('Calorie Intake', 'Blue', 'Mild Restriction. No Bingeing', '',
      Colors.blue, Colors.blue.shade100),
  Risk('Calorie Intake', 'White', 'Unscored', '0', Colors.white, Colors.white),
  Risk(
      'Engagement With Management Plan',
      'Red',
      'Violent when parents try to limit behaviour or encourage food/fluid intake. Parental violence in relation to feeding (hitting, force feeding)',
      '',
      Colors.red,
      Colors.red.shade100),
  Risk(
      'Engagement With Management Plan',
      'Amber',
      'Poor insight into eating problems. Lacks motivation to tackle eating problems. Resistance to changes required to gain weight. Parents unable to implement meal plan advice given by health care providers',
      '',
      Colors.amber,
      Colors.amber.shade100),
  Risk(
      'Engagement With Management Plan',
      'Green',
      'Some insight into eating problems. Some motivation to tackle eating problems, ambivalent towards changes required to gain weight but not actively resisting.',
      '',
      Colors.green,
      Colors.green.shade100),
  Risk(
      'Engagement With Management Plan',
      'Blue',
      'Some insight into eating problems. Motivated to tackle eating problems, ambivalence towards changes required to gain weight not apparent in behaviour',
      '',
      Colors.blue,
      Colors.blue.shade100),
  Risk('Engagement With Management Plan', 'White', 'Unscored', '0',
      Colors.white, Colors.white),
  Risk(
      'Activity and Exercise',
      'Red',
      'High levels of uncontrolled exercise (2hrs per day)',
      '',
      Colors.red,
      Colors.red.shade100),
  Risk(
      'Activity and Exercise',
      'Amber',
      'Moderate levels of uncontrolled exercise (>1 hr per day)',
      '',
      Colors.amber,
      Colors.amber.shade100),
  Risk(
      'Activity and Exercise',
      'Green',
      'Mild levels of uncontrolled exercise (less than 1 hr per day).',
      '',
      Colors.green,
      Colors.green.shade100),
  Risk('Activity and Exercise', 'Blue', 'No uncontrolled exercise', '',
      Colors.blue, Colors.blue.shade100),
  Risk('Activity and Exercise', 'White', 'Unscored', '0', Colors.white,
      Colors.white),
  Risk(
      'Self Harm and Suicide',
      'Red',
      'Self poisoning. Suicidal ideas with moderate-high risk of completed suicide',
      '',
      Colors.red,
      Colors.red.shade100),
  Risk(
      'Self Harm and Suicide',
      'Amber',
      'Cutting or similar behaviours. Suicidal ideas with low risk of completed suicide',
      '',
      Colors.amber,
      Colors.amber.shade100),
  Risk('Self Harm and Suicide', 'Green', 'No self harm/suicide.', '',
      Colors.green, Colors.green.shade100),
  Risk('Self Harm and Suicide', 'Blue', 'No self harm/suicide', '', Colors.blue,
      Colors.blue.shade100),
  Risk('Self Harm and Suicide', 'White', 'Unscored', '0', Colors.white,
      Colors.white),
  Risk(
      'Muscular Weakness',
      'Red',
      'Sit Up, Squat, Stand test: Unable to get up at all from squatting (score 0). Unable to sit up at all from lying flat (score 0)',
      '',
      Colors.red,
      Colors.red.shade100),
  Risk(
      'Muscular Weakness',
      'Amber',
      'Sit Up, Squat, Stand test: Unable to get up from squatting without using upper limbs (score 1) OR Unable to sit up from lying flat without using upper limbs (score 1)',
      '',
      Colors.amber,
      Colors.amber.shade100),
  Risk(
      'Muscular Weakness',
      'Green',
      'Sit Up, Squat, Stand test - Unable to get up without noticeable difficulty (score 2) OR Unable to sit up from lying flat without noticeable difficulty (score 2)',
      '',
      Colors.green,
      Colors.green.shade100),
  Risk(
      'Muscular Weakness',
      'Blue',
      'Sit Up, Squat, Stand test. Stands up from squat without any difficulty (score 3) OR Sits up from lying flat without any difficulty (score 3)',
      '',
      Colors.blue,
      Colors.blue.shade100),
  Risk('Muscular Weakness', 'White', 'Unscored', '0', Colors.white,
      Colors.white),
  Risk('Other Mental Health Diagnoses', 'Red', 'Confusion and delirium<', '',
      Colors.red, Colors.red.shade100),
  Risk(
      'Other Mental Health Diagnoses',
      'Amber',
      'Other major psychiatric co-diagnosis eg OCD, psychosis, depression',
      '',
      Colors.amber,
      Colors.amber.shade100),
  Risk(
      'Other Mental Health Diagnoses',
      'Green',
      'Poor attention and concentration',
      '',
      Colors.green,
      Colors.green.shade100),
  Risk('Other Mental Health Diagnoses', 'Blue', 'No other issues', '',
      Colors.blue, Colors.blue.shade100),
  Risk('Other Mental Health Diagnoses', 'White', 'Unscored', '0', Colors.white,
      Colors.white),
  Risk('Other', 'red', 'Acute Pancreatitis. Gastric or oesophageal rupture.',
      '', Colors.red, Colors.red.shade100),
  Risk(
      'Other',
      'Amber',
      'Mallory Weiss Tear. Gastro-oesophageal reflux. Gastritis. Pressure sores',
      '',
      Colors.amber,
      Colors.amber.shade100),
  Risk('Other', 'Green', 'No other issues', '', Colors.green,
      Colors.green.shade100),
  Risk('Other', 'Blue', 'No other issues', '', Colors.blue,
      Colors.blue.shade100),
  Risk('Other', 'White', 'Unscored', '0', Colors.white, Colors.white)
];
